OPENAI_API_KEY="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"
GM_OPENAI_API_KEY="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"
HUGGINGFACEHUB_API_TOKEN="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"
SUPABASE_URL="https://kmyzeeprjpsexyyxvcvy.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteXplZXByanBzZXh5eXh2Y3Z5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4Nzk1NzM2OSwiZXhwIjoyMDAzNTMzMzY5fQ.AbUJ0-Ggk5Z0dT3A_qM29_2HTDyTvkwWJmyBPtZOSIY"
