OPENAI_API_KEY="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"
GOOGLE_API_KEY="AIzaSyC4bcLOMHzkeQzclpW_wH9kQqR88fe4kME"
CUSTOM_SEARCH_ENGINE_ID="34bc9378eeb8a48e5"
SERPAPI_API_KEY ="b4c67bdf6b439523f85d1c62983c9cb4f22f1eb9811d2b20ca371f0f688ed920"
SUPABASE_URL="https://kmyzeeprjpsexyyxvcvy.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteXplZXByanBzZXh5eXh2Y3Z5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4Nzk1NzM2OSwiZXhwIjoyMDAzNTMzMzY5fQ.AbUJ0-Ggk5Z0dT3A_qM29_2HTDyTvkwWJmyBPtZOSIY"
XI_API_KEY="dc1f92e471db5fed8947b0b5496f1145"
